version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      TZ: UTC
      POSTGRES_DB: votacao
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app:
    image: desafio-votacao
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_URL: jdbc:postgresql://db:5432/votacao
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    ports:
      - "80:8080"
    depends_on:
      - db
    command: [ "java", "-jar", "app.jar" ]


networks:
  default:
    driver: bridge