
spring:
  application:
    name: desafio-votacao
  datasource:
    url:  ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

rabbitmq:
  host: localhost
  port: 5672
  username: ${MQ_USER}
  password: ${MQ_PASSWORD}

queue:
  name: fl-votos

logging:
  path: ./logs
  level:
    root: info
    dev.rafaelreis.desafiovotacao: debug

# Swagger UI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
